apiVersion: v1
kind: Pod
metadata:
  name: bandwidth-test
  namespace: {{ .Values.namespace }}
spec:
  restartPolicy: Never
  imagePullSecrets:
  - name: {{ .Values.imagePullSecret }}
  nodeSelector:
    kubernetes.io/hostname: {{ .Values.nodename }}
  containers:
  - image: {{ .Values.image }}
    name: bandwidth-test
    env:
    - name: BW
      value: "{{ .Values.bw }}"
    resources:
      limits:
        cpu: 1
        # memory: 50M
        nvidia.com/gpu: 8
      requests:
        cpu: 1
        # memory: 50M
        nvidia.com/gpu: 8