global:
  resolve_timeout: 5m
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
receivers:
  - name: cordoned-slack-alert
    slack_configs:
      - channel: openshift-monitoring
        api_url: >-
          https://hooks.slack.com/services/...
        username: Autopilot
        icon_emoji: ':warning:'
        text: A node has been cordoned - check node health
        send_resolved: true
  - name: low-pcie-bw-alert
    slack_configs:
      - channel: openshift-monitoring
        api_url: >-
          https://hooks.slack.com/services/...
        username: Autopilot
        icon_emoji: ':warning:'
        text: |-
          summary: {{ .CommonAnnotations.summary }}
          description: {{ .CommonAnnotations.description }}
        send_resolved: true
  - name: Default
  - name: Watchdog
  - name: nic-alert
    slack_configs:
      - channel: openshift-monitoring
        api_url: >-
          https://hooks.slack.com/services/...
        username: Autopilot
        icon_url: ':warning:'
        text: >-
          A node is not reachable - check NIC status {{ .CommonAnnotations.summary }}
  - name: remapped-alert
    slack_configs:
      - channel: openshift-monitoring
        api_url: >-
          https://hooks.slack.com/services/...
        username: Autopilot
        icon_emoji: ':warning:'
        text: |-
          summary: {{ .CommonAnnotations.summary }}
          description: {{ .CommonAnnotations.description }}
route:
  receiver: Default
  repeat_interval: 12h
  routes:
    - receiver: low-pcie-bw-alert
      matchers:
        - pcie = autopilot
    - receiver: cordoned-slack-alert
      matchers:
        - cordon = autopilot
    - receiver: Watchdog
      matchers:
        - alertname = Watchdog
    - receiver: nic-alert
      match:
        nic: autopilot
    - receiver: remapped-alert
      match:
        remapped: autopilot
