global:
  resolve_timeout: 5m
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
receivers:
  - name: cordon-event
    slack_configs:
      - channel: ocp
        api_url: >-
          https://hooks.slack.com/services/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
        text: node is cordoned
        send_resolved: true
  - name: cordoned-slack-alert
    slack_configs:
      - channel: monitoring
        api_url: >-
          https://hooks.slack.com/services/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
        send_resolved: true
        icon_emoji: ':warning:'
        text: Node is cordoned - check node health
route:
  group_by:
    - namespace
  group_interval: 1m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - receiver: cordon-event
      match_re:
        cordon: autopilot
    - receiver: cordoned-slack-alert
      match_re:
        cordon: autopilot