global:
  resolve_timeout: 5m
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
  - equal:
      - namespace
    source_matchers:
      - alertname = InfoInhibitor
    target_matchers:
      - severity = info
receivers:
  - name: Default
  - name: Watchdog
  - name: Critical
  - name: 'null'
  - name: autopilot-pcie
    slack_configs:
      - channel: autopilot-pokmvp-alerts
        api_url: >-
          https://hooks.slack.com/services/...
        text: 'summary: {{ .CommonAnnotations.summary }}'
        send_resolved: true
        username: Autopilot
  - name: autopilot-ping
    slack_configs:
      - channel: autopilot-pokmvp-alerts
        api_url: >-
          https://hooks.slack.com/services/...
        text: 'summary: {{ .CommonAnnotations.summary }}'
        send_resolved: true
        username: Autopilot
  - name: autopilot-remapped
    slack_configs:
      - channel: autopilot-pokmvp-alerts
        api_url: >-
          https://hooks.slack.com/services/...
        text: 'summary: {{ .CommonAnnotations.summary }}'
        send_resolved: true
        username: Autopilot
  - name: autopilot-dcgm
    slack_configs:
      - channel: autopilot-pokmvp-alerts
        api_url: >-
          https://hooks.slack.com/services/...
        text: 'summary: {{ .CommonAnnotations.summary }}'
        send_resolved: true
        username: Autopilot
  - name: autopilot-cordon
    slack_configs:
      - channel: autopilot-pokmvp-alerts
        api_url: >-
          https://hooks.slack.com/services/...
        text: 'summary: {{ .CommonAnnotations.summary }}'
        send_resolved: true
        username: Autopilot
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - alertname = InfoInhibitor
      receiver: 'null'
    - receiver: autopilot-pcie
      match:
        pcie: autopilot
    - receiver: autopilot-remapped
      match:
        remapped: autopilot
    - receiver: autopilot-dcgm
      match:
        dcgm: autopilot
    - receiver: autopilot-ping
      match:
        ping: autopilot
    - receiver: autopilot-cordon
      match:
        cordon: autopilot
