apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pcie-alert
  namespace: openshift-monitoring
  labels:
    pcie: autopilot
spec:
  groups:
  - name: autopilot
    rules:
    - alert: PcieAlert
      annotations:
        description: A node has a PCIE bandwidth of 4 or less
        summary: A node has a PCIE bandwidth of 4 or less
      expr: sum (autopilot_health_checks{health="pciebw"}<=4) by (node, deviceid) > 0
      for: 1m
      labels:
        severity: critical
        cordon: autopilot