apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autopilot-endpoint-reader
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autopilot-endpoint-reader
subjects:
- kind: ServiceAccount
  name: autopilot-endpoint-reader # Name is case sensitive
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: autopilot-endpoint-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autopilot-endpoint-reader
  namespace: {{ .Values.namespace  }}
---
apiVersion: v1
kind: Pod
metadata:
  name: system-check
spec:
  restartPolicy: Never
  serviceAccountName: autopilot-endpoint-reader
  imagePullSecrets:
  - name: {{ .Values.imagePullSecret }}
  # nodeSelector:
  #   kubernetes.io/hostname: {{ .Values.nodename }}
  containers:
  - image: {{ .Values.image }}
    name: system-check
    args: ['--service={{ .Values.autopilotService }}', '--namespace={{ .Values.autopilotNamespace }}', '--nodes={{ .Values.targetNode }}', '--check={{ .Values.testType }}', '--batchSize={{ .Values.batchSize }}']
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    resources:
      limits:
        cpu: 4
        memory: 500M
      requests:
        cpu: 4
        memory: 500M
