{{- if .Values.pullSecrets.create -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pullSecrets.imagePullSecretData }}
kind: Secret
metadata:
  name: autopilot-pull
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
{{- end}}