{{- if .Values.namespace.create -}}
kind: Namespace
apiVersion: v1
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: {{ .Values.namespace.name }}
spec:
  finalizers:
  - kubernetes
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autopilot
  namespace: {{ .Values.namespace.name  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autopilot
  namespace: {{ .Values.namespace.name  }}
rules:
- apiGroups: ["my.domain"]
  resources: ["healthcheckreports"]
  verbs: ["create", "get", "list"]
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["list","patch","watch"]
# - apiGroups: ["kubeflow.org"]
#   resources: ["pytorchjobs"]
#   verbs: ["list", "get"]
# - apiGroups: ["apps/v1"]
#   resources: ["replicasets"]
#   verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autopilot 
  namespace: {{ .Values.namespace.name  }}
subjects:
- kind: ServiceAccount
  name: autopilot 
  namespace: {{ .Values.namespace.name  }} 
roleRef: 
  kind: ClusterRole
  name: autopilot 
  apiGroup: rbac.authorization.k8s.io
