apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test 
  name: eletonia-deployment
  #namespace: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
      - name: us-icr-io
      containers:
        - image: us.icr.io/cil15-shared-registry/autopilot/reachability:v0
          command:
            - sh
            - -c
            - |
              python metrics-entrypoint.py
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always 
          name: netreach
          resources:
            limits:
              #nvidia.com/gpu: 8
              cpu: 4 
              memory: 1Gi
            requests:
              #nvidia.com/gpu: 8
              cpu: 4
              memory: 1Gi
